# Generated by Django 4.0.2 on 2022-02-11 12:03

import api.enum.statusRequest
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RequestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('project_link', models.CharField(max_length=70)),
                ('contract_address', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=api.enum.statusRequest.StatusRequest['pending'])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.client')),
            ],
        ),
    ]
