# Generated by Django 4.0.2 on 2022-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_wallet_requesttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=100)),
                ('address_contract', models.CharField(max_length=100)),
                ('abi', models.CharField(max_length=500)),
                ('address_wallet', models.CharField(max_length=100)),
            ],
        ),
    ]
