# Generated by Django 4.0.2 on 2022-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deployedcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedcontract',
            name='abi',
            field=models.TextField(),
        ),
    ]
