# Generated by Django 4.0.2 on 2022-02-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deployedcontract_abi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedcontract',
            name='abi',
        ),
    ]
